### ISSUE TITLE
Currently is not x86-able (32bits)

### ISSUE THREAD

**Issue by lubiedo** [d-we/binja-golang-symbol-restore#2]
Is only converting quad addresses: https://github.com/d-we/binja-golang-symbol-restore/blob/59e8843466a31e860f915309678a5ba042d13926/golang_symbol_restore.py#L30

I manually changed it to `<L` and restoration worked as expected. I will see if I can push a PR later.

**Comment by lubiedo** [comment]
Created PR https://github.com/d-we/binja-golang-symbol-restore/pull/3 for this.

**Comment by d-we** [comment]
Thank you very much for reporting and also fixing! :)

**Comment by d-we** [comment]
I merged your PR in c6d4eee3cf5fc8cad5453e509119d31e88d4f8b3
